#include "File.h"




void File::Rename(Pattern pat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008DD begin
{
}
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008DD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

String File::GetSuffix()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008FC begin
{
}
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008FC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void File::Copy(Pattern pat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008FE begin
{
}
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008FE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
