#include "ReleasePage.h"




void ReleasePage::FillRelease(Release rel)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:0000000000000895 begin
{
}
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:0000000000000895 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
