#include "Settings.h"




void Settings::ParseArgs()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008C1 begin
{
}
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008C1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
