#include "TagHeader.h"




String TagHeader::GetArtist()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008EC begin
{
}
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008EC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

String TagHeader::GetTitle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008EE begin
{
}
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008EE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer TagHeader::GetNumber()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008F0 begin
{
}
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008F0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
