#include "Track.h"




Boolean Track::FilledEnough(Pattern pat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008F8 begin
{
}
// section 127-0-0-1-5b3a7232:13146d9a2ca:-8000:00000000000008F8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
